"""some xtra changes

Revision ID: 18201f21f047
Revises: 68f8aaa702d7
Create Date: 2023-09-26 18:19:21.557731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18201f21f047'
down_revision = '68f8aaa702d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'units', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'units', ['course_id'], ['code'])
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
