""" updating students to have a current module column

Revision ID: 3c70c83e90cb
Revises: 
Create Date: 2023-10-04 14:08:26.525169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c70c83e90cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_module', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("student_year", 'years', ['current_module'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_module')

    # ### end Alembic commands ###
