"""changing the dataase types to fit new app 

Revision ID: 4cccec74050f
Revises: 
Create Date: 2023-10-06 21:14:56.546708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cccec74050f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('email')
    )
    op.create_table('years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('lecturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=16), nullable=False),
    sa.Column('mname', sa.String(length=16), nullable=False),
    sa.Column('sname', sa.String(length=16), nullable=False),
    sa.Column('uname', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uname')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mark_id', sa.Integer(), nullable=False),
    sa.Column('firstattempt', sa.Float(), nullable=False),
    sa.Column('secondattempt', sa.Float(), nullable=True),
    sa.Column('thirdattempt', sa.Float(), nullable=True),
    sa.Column('finalattempt', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['mark_id'], ['marks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'enrollments', ['enrollment_id'], ['id'])
        batch_op.drop_column('course_id')
        batch_op.drop_column('student_id')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('current_module', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'departments', ['department'], ['name'])
        batch_op.create_foreign_key(None, 'years', ['current_module'], ['id'])

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('department', sa.String(length=16), nullable=False))
        batch_op.create_foreign_key(None, 'years', ['module'], ['id'])
        batch_op.create_foreign_key(None, 'departments', ['department'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('department')
        batch_op.drop_column('module')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_module')
        batch_op.drop_column('department')

    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'units', ['course_id'], ['id'])
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])
        batch_op.drop_column('enrollment_id')

    op.drop_table('results')
    op.drop_table('lecturers')
    op.drop_table('years')
    op.drop_table('departments')
    # ### end Alembic commands ###
