"""some xtra changes

Revision ID: 68f8aaa702d7
Revises: 
Create Date: 2023-09-26 18:13:04.840158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f8aaa702d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('cat1', sa.Float(), nullable=False),
    sa.Column('Cat2', sa.Float(), nullable=False),
    sa.Column('cat3', sa.Float(), nullable=False),
    sa.Column('assignment1', sa.Float(), nullable=False),
    sa.Column('assignment2', sa.Float(), nullable=False),
    sa.Column('assignment3', sa.Float(), nullable=False),
    sa.Column('practicals', sa.Float(), nullable=False),
    sa.Column('mainExam', sa.Float(), nullable=False),
    sa.Column('overallmarks', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['units.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('firstattempt', sa.Float(), nullable=False),
    sa.Column('secondattempt', sa.Float(), nullable=False),
    sa.Column('thirdattempt', sa.Float(), nullable=False),
    sa.Column('finalattempt', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['units.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('marks')
    # ### end Alembic commands ###
